// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.10;

import {IERC20Detailed} from "../../interfaces/IERC20Detailed.sol";
import {IERC4626} from "../../interfaces/IERC4626.sol";
import {SafeERC20Upgradeable} from "@openzeppelin/contracts-upgradeable/token/ERC20/utils/SafeERC20Upgradeable.sol";
import {OwnableUpgradeable} from "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import {Initializable} from "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import {ReentrancyGuardUpgradeable} from "@openzeppelin/contracts-upgradeable/security/ReentrancyGuardUpgradeable.sol";

error NotAllowed();
error InvalidAddress();
error InvalidAmount();
error AlreadyInitialized();
error InsufficientBorrowable();

/// @title ProgrammableBorrower
/// @dev Borrower adapter used by `IdleCDOEpochVariant` for revolving-credit facilities.
/// It has two jobs:
/// 1. keep undrawn capital parked inside an ERC4626 vault (for example a Morpho vault)
/// 2. track interest owed by the real borrower when that capital is temporarily drawn
///
/// IdleCDO only orchestrates the epoch lifecycle and reads a single stop-epoch interest value from
/// this contract. The detailed split between vault yield and borrower interest stays here.
contract ProgrammableBorrower is Initializable, OwnableUpgradeable, ReentrancyGuardUpgradeable {
  using SafeERC20Upgradeable for IERC20Detailed;

  uint256 internal constant ONE_TRANCHE_TOKEN = 1e18;
  uint256 internal constant YEAR = 365 days;

  /// @notice underlying token (must match the vault asset)
  IERC20Detailed public underlyingToken;
  /// @notice ERC4626 vault where funds are deployed (eg Morpho supply vault)
  IERC4626 public morphoVault;
  /// @notice IdleCDOEpochVariant address allowed to pull funds
  address public idleCDO;
  /// @notice real borrower address allowed to draw/repay
  address public borrower;

  /// @notice fixed APR charged to borrower debt (100e18 = 100% APR)
  uint256 public borrowerApr;
  /// @notice outstanding borrower principal
  uint256 public borrowerPrincipal;
  /// @notice borrower contractual interest accrued but not yet settled to IdleCDO
  /// @dev This tracks only the real borrower's credit-facility interest and is independent from
  /// gains or losses generated by the Morpho sleeve.
  uint256 public borrowerInterestAccrued;
  /// @notice borrower contractual interest already settled to IdleCDO but not yet repaid
  /// @dev This can be greater than the same epoch's net pool interest if the Morpho sleeve had a
  /// loss. Morpho PnL stays in pool accounting; borrower debt stays purely contractual.
  uint256 public borrowerInterestDebt;
  /// @notice last timestamp borrower interest was accrued
  uint256 public lastBorrowerAccrual;

  /// @notice Morpho assets held at epoch start (baseline)
  uint256 public epochStartMorphoAssets;
  /// @notice cumulative assets deposited to Morpho during epoch
  uint256 public epochDepositedToMorpho;
  /// @notice cumulative assets withdrawn from Morpho during epoch
  uint256 public epochWithdrawnFromMorpho;
  /// @notice whether epoch accounting is active
  bool public epochAccountingActive;
  /// @notice pending withdraw requests amount reserved for the epoch
  uint256 public epochPendingWithdraws;

  event DepositedIntoMorpho(uint256 assets, uint256 shares);
  event WithdrawnFromMorpho(uint256 assets, uint256 shares, address indexed receiver);
  event RedeemedFromMorpho(uint256 shares, uint256 assets, address indexed receiver);
  event MorphoVaultSet(address indexed newMorphoVault);
  event BorrowerSet(address indexed newBorrower);
  event BorrowerAprSet(uint256 newApr);
  event Borrowed(uint256 assets);
  event Repaid(uint256 assets, uint256 interestPaid, uint256 principalPaid);
  event EpochAccountingStarted(uint256 startAssets);
  event EpochAccountingStopped();
  event BorrowerInterestSettled(uint256 amount);

  /// @custom:oz-upgrades-unsafe-allow constructor
  constructor() {
    // Mark the implementation as already initialized in its own storage. A proxy starts from
    // zeroed storage, so `initialize` remains available only through the proxy instance.
    underlyingToken = IERC20Detailed(address(1));
  }

  /// @notice initialize the contract
  /// @param _underlyingToken address of the underlying token
  /// @param _morphoVault ERC4626 vault where funds will be deployed
  /// @param _idleCDO IdleCDOEpochVariant contract allowed to pull funds
  /// @param _owner owner address
  function initialize(
    address _underlyingToken,
    address _morphoVault,
    address _idleCDO,
    address _owner
  ) external initializer {
    if (address(underlyingToken) != address(0)) revert AlreadyInitialized();
    if (
      _underlyingToken == address(0) ||
      _morphoVault == address(0) ||
      _owner == address(0) ||
      _idleCDO == address(0) ||
      IERC4626(_morphoVault).asset() != _underlyingToken
    ) {
      revert InvalidAddress();
    }

    __Ownable_init();
    __ReentrancyGuard_init();
    transferOwnership(_owner);

    IERC4626 _vault = IERC4626(_morphoVault);
    underlyingToken = IERC20Detailed(_underlyingToken);
    morphoVault = _vault;
    idleCDO = _idleCDO;

    // Set approvals for morpho vault and IdleCDO
    _allowUnlimitedSpend(_underlyingToken, _morphoVault);
    _allowUnlimitedSpend(_underlyingToken, _idleCDO);
  }

  /// @notice Set the vault used to deploy idle funds.
  /// @dev This does not migrate an existing position. The owner must first withdraw from the old
  /// vault, otherwise assets can remain stranded there and the live accounting views will stop
  /// including them after the switch.
  /// @param _morphoVault new ERC4626 vault address
  function setMorphoVault(address _morphoVault) external onlyOwner {
    if (_morphoVault == address(0) || IERC4626(_morphoVault).asset() != address(underlyingToken)) {
      revert InvalidAddress();
    }
    underlyingToken.safeApprove(address(morphoVault), 0);
    morphoVault = IERC4626(_morphoVault);
    _allowUnlimitedSpend(address(underlyingToken), _morphoVault);
    emit MorphoVaultSet(_morphoVault);
  }

  /// @notice Set the real borrower allowed to draw and repay funds.
  /// @param _borrower borrower EOA or controller address
  function setBorrower(address _borrower) external onlyOwner {
    if (_borrower == address(0)) {
      revert InvalidAddress();
    }
    borrower = _borrower;
    emit BorrowerSet(_borrower);
  }

  /// @notice Set the fixed APR charged on drawn borrower principal (100e18 = 100% APR).
  /// @dev Checkpoints accrued interest at the old rate before applying the new APR.
  /// @param _apr borrower APR expressed as a percentage scaled by 1e18
  function setBorrowerApr(uint256 _apr) external onlyOwner {
    _accrueBorrowerInterest();
    borrowerApr = _apr;
    emit BorrowerAprSet(_apr);
  }

  /// @notice Hook called by IdleCDOEpochVariant when a new epoch starts.
  /// It deposits all on-hand assets into Morpho and starts accounting.
  /// @param _pendingWithdraws pending withdraw requests amount to reserve for epoch end.
  function onStartEpoch(uint256 _pendingWithdraws) external nonReentrant {
    _checkOnlyIdleCDO();
    _accrueBorrowerInterest();
    // Reserve the amount IdleCDO expects to pull back at stopEpoch before the real borrower can draw again.
    epochPendingWithdraws = _pendingWithdraws;
    // Snapshot total assets before re-depositing idle cash so the epoch principal baseline uses the
    // exact pre-deposit amount instead of a post-deposit share-conversion round-down.
    uint256 startAssets = underlyingToken.balanceOf(address(this)) + _currentMorphoAssets();
    // Any idle balance left on the contract between epochs is parked immediately into Morpho.
    _depositAllToMorphoInternal(0);
    _startEpochAccountingInternal(startAssets);
  }

  /// @notice Hook called by IdleCDOEpochVariant before stopping an epoch.
  /// Withdraws enough liquidity from Morpho so IdleCDO can pull funds.
  /// @param _amountRequired total amount IdleCDO will pull via transferFrom.
  function onStopEpoch(uint256 _amountRequired) external nonReentrant {
    _checkOnlyIdleCDO();
    _accrueBorrowerInterest();

    uint256 onHand = underlyingToken.balanceOf(address(this));
    if (_amountRequired > onHand) {
      uint256 shortfall = _amountRequired - onHand;
      // Cap withdrawal to what Morpho can actually provide. If total on-hand is still
      // insufficient after a partial withdrawal, the CDO's transferFrom will revert and
      // trigger default handling with ProgrammableBorrower state properly settled.
      uint256 maxW = morphoVault.maxWithdraw(address(this));
      uint256 toWithdraw = shortfall > maxW ? maxW : shortfall;
      if (toWithdraw > 0) {
        uint256 shares = morphoVault.withdraw(toWithdraw, address(this), address(this));
        if (epochAccountingActive) {
          epochWithdrawnFromMorpho += toWithdraw;
        }
        emit WithdrawnFromMorpho(toWithdraw, shares, address(this));
      }
    }

    // Stop reserving epoch-end withdraw liquidity once IdleCDO has started the stop flow.
    epochPendingWithdraws = 0;
    epochAccountingActive = false;
    emit EpochAccountingStopped();
  }

  /// @notice Settle accrued borrower interest into debt after IdleCDO successfully fronted it.
  /// @dev Called by IdleCDO only on the success path of `stopEpoch`. If the CDO's `transferFrom`
  /// fails (default), this is never called and borrower interest stays in `borrowerInterestAccrued`.
  /// Borrower debt is intentionally settled at the full contractual borrower-interest amount,
  /// without netting Morpho gains or losses against it.
  function settleBorrowerInterest() external nonReentrant {
    _checkOnlyIdleCDO();
    uint256 settled = borrowerInterestAccrued;
    if (settled != 0) {
      borrowerInterestAccrued = 0;
      borrowerInterestDebt += settled;
    }
    emit BorrowerInterestSettled(settled);
  }

  /// @notice Reset the epoch accounting baseline for a newly started epoch.
  /// @dev `_startAssets` is the exact pre-start total asset amount. Using that value avoids
  /// immediately baking vault share-conversion rounding into the new epoch's interest accounting.
  /// @param _startAssets total assets controlled by the programmable borrower at epoch start
  function _startEpochAccountingInternal(uint256 _startAssets) internal {
    epochStartMorphoAssets = _startAssets;
    epochDepositedToMorpho = 0;
    epochWithdrawnFromMorpho = 0;
    epochAccountingActive = true;
    lastBorrowerAccrual = block.timestamp;
    emit EpochAccountingStarted(epochStartMorphoAssets);
  }

  /// @notice interest accrued in Morpho since the last `startEpochAccounting`
  function morphoInterestAccrued() public view returns (uint256) {
    (uint256 interest,) = _morphoNetInterest();
    return interest;
  }

  /// @notice borrower interest accrued since epoch start up to now (includes uncheckpointed interest)
  function borrowerInterestAccruedNow() public view returns (uint256) {
    uint256 principal = borrowerPrincipal;
    uint256 accrued = borrowerInterestAccrued;
    uint256 last = lastBorrowerAccrual;
    if (principal == 0 || last == 0 || borrowerApr == 0) return accrued;
    uint256 elapsed = block.timestamp - last;
    uint256 additional = elapsed == 0
      ? 0
      : principal * (borrowerApr / 100) * elapsed / (YEAR * ONE_TRANCHE_TOKEN);
    return accrued + additional;
  }

  /// @notice total borrower interest still owed by the real borrower
  function borrowerInterestOwedNow() external view returns (uint256) {
    return borrowerInterestDebt + borrowerInterestAccruedNow();
  }

  /// @notice unrealized loss from the Morpho vault position since epoch start
  function morphoLoss() public view returns (uint256) {
    (,uint256 loss) = _morphoNetInterest();
    return loss;
  }

  /// @notice Total net epoch interest due to the pool at stop.
  /// @dev This is the single value read by IdleCDO to price the epoch: borrower contractual
  /// interest plus positive Morpho PnL minus Morpho losses. It is a pool-facing value, so it can
  /// be lower than `borrowerInterestDebt` when the borrower still owes full contractual interest
  /// but the Morpho sleeve suffered a loss.
  function totalInterestDueNow() external view returns (uint256) {
    (uint256 morphoInterest, uint256 loss) = _morphoNetInterest();
    uint256 totalGain = morphoInterest + borrowerInterestAccruedNow();
    return totalGain > loss ? totalGain - loss : 0;
  }

  /// @notice Compute the net Morpho delta split into interest and loss (mutually exclusive).
  function _morphoNetInterest() internal view returns (uint256 interest, uint256 loss) {
    if (!epochAccountingActive) return (0, 0);
    uint256 earnedAssets = _currentMorphoAssets() + epochWithdrawnFromMorpho;
    uint256 principalAssets = epochStartMorphoAssets + epochDepositedToMorpho;
    if (earnedAssets > principalAssets) {
      interest = earnedAssets - principalAssets;
    } else {
      loss = principalAssets - earnedAssets;
    }
  }

  /// @notice current borrowable liquidity excluding reserved withdraw requests
  function availableToBorrow() public view returns (uint256) {
    uint256 totalAssets = underlyingToken.balanceOf(address(this)) + _currentMorphoAssets();
    // Interest is minted (not pulled as cash), so only pending withdraw requests need reservation.
    uint256 reserved = epochPendingWithdraws;
    return totalAssets <= reserved ? 0 : totalAssets - reserved;
  }

  /// @notice Emergency escape: redeem Morpho shares back to this contract.
  /// @dev Owner-only. Pass 0 to redeem all shares.
  /// @param _shares number of vault shares to redeem (0 = redeem all)
  /// @return assets amount of underlying redeemed
  function emergencyExitMorpho(uint256 _shares) external nonReentrant onlyOwner returns (uint256 assets) {
    if (_shares == 0) {
      _shares = morphoVault.balanceOf(address(this));
    }
    if (_shares == 0) revert InvalidAmount();
    assets = morphoVault.redeem(_shares, address(this), address(this));
    if (epochAccountingActive) {
      epochWithdrawnFromMorpho += assets;
    }
    emit RedeemedFromMorpho(_shares, assets, address(this));
  }

  /// @notice Move the contract's full idle underlying balance into Morpho.
  /// @param _principalAssets Portion of the deposited assets that should extend the epoch principal
  /// baseline instead of being recognized as current-epoch profit.
  function _depositAllToMorphoInternal(uint256 _principalAssets) internal {
    uint256 assets = underlyingToken.balanceOf(address(this));
    if (assets == 0) return;
    uint256 shares = morphoVault.deposit(assets, address(this));
    if (epochAccountingActive && _principalAssets != 0) {
      epochDepositedToMorpho += _principalAssets;
    }
    emit DepositedIntoMorpho(assets, shares);
  }

  /// @notice Draw funds from the revolving-credit facility.
  /// @dev Only the configured real borrower can call this while an epoch is active. If there is
  /// not enough on-hand liquidity, the shortfall is first withdrawn from Morpho.
  /// @param assets amount of underlying to draw
  /// @return withdrawnShares shares burned from Morpho, if any liquidity had to be freed first
  function borrow(uint256 assets) external nonReentrant returns (uint256 withdrawnShares) {
    if (msg.sender != borrower || !epochAccountingActive) revert NotAllowed();
    if (assets == 0) revert InvalidAmount();

    // Borrows are capped by the live "reserved vs free" view so epoch-end obligations always stay covered.
    if (assets > availableToBorrow()) revert InsufficientBorrowable();

    _accrueBorrowerInterest();

    uint256 onHand = underlyingToken.balanceOf(address(this));
    if (onHand < assets) {
      uint256 shortfall = assets - onHand;
      withdrawnShares = morphoVault.withdraw(shortfall, address(this), address(this));
      if (epochAccountingActive) {
        epochWithdrawnFromMorpho += shortfall;
      }
      emit WithdrawnFromMorpho(shortfall, withdrawnShares, address(this));
    }

    borrowerPrincipal += assets;
    underlyingToken.safeTransfer(borrower, assets);
    emit Borrowed(assets);
  }

  /// @notice Repay drawn funds back into the facility.
  /// @dev Repayments are applied in this order:
  /// 1. `borrowerInterestDebt` already fronted by IdleCDO
  /// 2. `borrowerInterestAccrued` not yet fronted
  /// 3. `borrowerPrincipal`
  ///
  /// Any excess over the tracked debt simply remains on this contract. When an epoch is active,
  /// the received funds are redeployed into Morpho before the function returns.
  /// @param assets amount of underlying to repay
  /// @return interestPaid interest component cleared by the repayment
  /// @return principalPaid principal component cleared by the repayment
  function repay(uint256 assets) external nonReentrant returns (uint256 interestPaid, uint256 principalPaid) {
    if (msg.sender != borrower) revert NotAllowed();
    if (assets == 0) revert InvalidAmount();

    _accrueBorrowerInterest();

    underlyingToken.safeTransferFrom(borrower, address(this), assets);
    uint256 totalRepaidAssets = assets;
    uint256 currentEpochInterestPaid;

    // First clear interest that IdleCDO already fronted during previous epoch settlements.
    uint256 settledInterestDue = borrowerInterestDebt;
    if (settledInterestDue != 0) {
      if (assets >= settledInterestDue) {
        interestPaid = settledInterestDue;
        borrowerInterestDebt = 0;
        assets -= settledInterestDue;
      } else {
        borrowerInterestDebt = settledInterestDue - assets;
        emit Repaid(assets, assets, 0);
        if (epochAccountingActive) {
          // While an epoch is active, even partial repayments are parked back into Morpho immediately.
          // This repayment only clears previously-fronted debt, so it should not count as new epoch profit.
          _depositAllToMorphoInternal(assets);
        }
        return (assets, 0);
      }
    }

    // Then clear interest accrued but not yet fronted by IdleCDO.
    uint256 accruedInterestDue = borrowerInterestAccrued;
    if (assets >= accruedInterestDue) {
      interestPaid += accruedInterestDue;
      currentEpochInterestPaid = accruedInterestDue;
      borrowerInterestAccrued = 0;
      assets -= accruedInterestDue;

      // Only after all interest is covered can the remainder reduce outstanding principal.
      uint256 principalDue = borrowerPrincipal;
      principalPaid = assets > principalDue ? principalDue : assets;
      borrowerPrincipal = principalDue - principalPaid;
    } else {
      interestPaid += assets;
      currentEpochInterestPaid = assets;
      borrowerInterestAccrued = accruedInterestDue - assets;
    }

    emit Repaid(interestPaid + principalPaid, interestPaid, principalPaid);
    if (epochAccountingActive) {
      // Current-epoch borrower interest must remain visible as profit at stopEpoch, while principal,
      // previously-fronted debt, and any excess repayment should only extend the epoch principal baseline.
      _depositAllToMorphoInternal(totalRepaidAssets - currentEpochInterestPaid);
    }
  }

  /// @notice Return the total exposure in underlying terms (on-hand plus Morpho position).
  function totalUnderlying() external view returns (uint256) {
    return underlyingToken.balanceOf(address(this)) + _currentMorphoAssets();
  }

  /// @notice Return the current Morpho vault share balance held by this contract.
  function morphoSharesBalance() external view returns (uint256) {
    return morphoVault.balanceOf(address(this));
  }

  /// @notice Convert the current vault share position into underlying terms.
  function _currentMorphoAssets() internal view returns (uint256) {
    uint256 shares = morphoVault.balanceOf(address(this));
    return shares == 0 ? 0 : morphoVault.convertToAssets(shares);
  }

  /// @notice Checkpoint borrower interest up to `block.timestamp`.
  /// @dev The first call only seeds the accrual clock. When principal or APR is zero we still
  /// move the timestamp forward so interest starts accruing cleanly from the next state change.
  function _accrueBorrowerInterest() internal {
    uint256 last = lastBorrowerAccrual;
    uint256 principal = borrowerPrincipal;
    if (last == 0 || principal == 0 || borrowerApr == 0) {
      lastBorrowerAccrual = block.timestamp;
      return;
    }
    uint256 elapsed = block.timestamp - last;
    if (elapsed == 0) {
      return;
    }
    borrowerInterestAccrued += principal * (borrowerApr / 100) * elapsed / (YEAR * ONE_TRANCHE_TOKEN);
    lastBorrowerAccrual = block.timestamp;
  }

  /// @notice Revert unless the caller is the configured IdleCDO.
  function _checkOnlyIdleCDO() internal view {
    if (msg.sender != idleCDO) revert NotAllowed();
  }

  /// @notice Emergency token rescue.
  /// @dev This is fully owner-trusted and can move the underlying as well, so it should only be
  /// used to recover stuck funds or to unwind a broken external integration.
  /// @param _token token address to transfer
  /// @param _to recipient
  /// @param _amount amount to transfer
  function rescueTokens(address _token, address _to, uint256 _amount) external onlyOwner {
    if (_to == address(0)) revert InvalidAddress();
    IERC20Detailed(_token).safeTransfer(_to, _amount);
  }

  /// @dev Set allowance for `_token` to unlimited for `_spender`.
  /// Both the vault and IdleCDO are trusted integrations, so the contract keeps a standing approval.
  /// @param _token token address
  /// @param _spender spender address
  function _allowUnlimitedSpend(address _token, address _spender) internal {
    IERC20Detailed(_token).safeIncreaseAllowance(_spender, type(uint256).max);
  }
}
