// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.10;

import {IERC20Detailed} from "../../interfaces/IERC20Detailed.sol";
import {IERC4626} from "../../interfaces/IERC4626.sol";
import {SafeERC20Upgradeable} from "@openzeppelin/contracts-upgradeable/token/ERC20/utils/SafeERC20Upgradeable.sol";
import {OwnableUpgradeable} from "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import {Initializable} from "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import {ReentrancyGuardUpgradeable} from "@openzeppelin/contracts-upgradeable/security/ReentrancyGuardUpgradeable.sol";

error NotAllowed();
error InvalidAddress();
error InvalidAmount();
error AlreadyInitialized();
error InsufficientBorrowable();

/// @title ProgrammableBorrower
/// @dev Borrower adapter used by `IdleCDOEpochVariant` for revolving-credit facilities.
/// It has two jobs:
/// 1. keep undrawn capital parked inside an ERC4626 vault
/// 2. track interest owed by the real borrower when that capital is temporarily drawn
///
/// IdleCDOEpochVariant only orchestrates the epoch lifecycle and reads a single stop-epoch interest value from
/// this contract. The detailed split between vault yield and borrower interest stays here.
contract ProgrammableBorrower is Initializable, OwnableUpgradeable, ReentrancyGuardUpgradeable {
  using SafeERC20Upgradeable for IERC20Detailed;

  uint256 internal constant ONE_TRANCHE_TOKEN = 1e18;
  uint256 internal constant YEAR = 365 days;

  /// @notice underlying token (must match the vault asset)
  IERC20Detailed public underlyingToken;
  /// @notice ERC4626 vault where idle funds are deployed
  IERC4626 public vault;
  /// @notice IdleCDOEpochVariant address allowed to pull funds
  address public idleCDO;
  /// @notice real borrower address allowed to draw/repay
  address public borrower;

  /// @notice fixed APR charged to borrower debt (100e18 = 100% APR)
  uint256 public borrowerApr;
  /// @notice outstanding borrower principal
  uint256 public borrowerPrincipal;
  /// @notice borrower contractual interest accrued but not yet settled to IdleCDO
  /// @dev This tracks only the real borrower's credit-facility interest and is independent from
  /// gains or losses generated by the vault sleeve.
  uint256 public borrowerInterestAccrued;
  /// @notice borrower contractual interest already settled to IdleCDO but not yet repaid
  /// @dev This can be greater than the same epoch's net pool interest if the vault sleeve had a
  /// loss. Vault PnL stays in pool accounting; borrower debt stays purely contractual.
  uint256 public borrowerInterestDebt;
  /// @notice last timestamp borrower interest was accrued
  uint256 public lastBorrowerAccrual;
  /// @notice Vault assets held at epoch start (baseline)
  uint256 public epochStartVaultAssets;
  /// @notice cumulative assets deposited to vault during epoch
  uint256 public epochDepositedToVault;
  /// @notice cumulative assets withdrawn from vault during epoch
  uint256 public epochWithdrawnFromVault;
  /// @notice whether epoch accounting is active
  bool public epochAccountingActive;
  /// @notice pending withdraw requests amount reserved for the epoch
  uint256 public epochPendingWithdraws;
  /// @notice allowed to operate routine facility admin actions
  address public manager;
  /// @notice vault assets left invested when the previous epoch stopped
  /// @dev Used to measure vault PnL generated during the buffer so it is carried into the next epoch.
  uint256 public bufferStartVaultAssets;
  /// @notice net vault PnL earned during the buffer and not yet realized by IdleCDO
  /// @dev Positive values represent gains, negative values represent losses.
  int256 public bufferedVaultDelta;

  event DepositedIntoVault(uint256 assets, uint256 shares);
  event WithdrawnFromVault(uint256 assets, uint256 shares, address indexed receiver);
  event RedeemedFromVault(uint256 shares, uint256 assets, address indexed receiver);
  event VaultUpdated(address indexed newVault);
  event BorrowerSet(address indexed newBorrower);
  event BorrowerAprSet(uint256 newApr);
  event Borrowed(uint256 assets);
  event Repaid(uint256 assets, uint256 interestPaid, uint256 principalPaid);
  event EpochAccountingStarted(uint256 startAssets);
  event EpochAccountingStopped();
  event BorrowerInterestSettled(uint256 amount);

  /// @custom:oz-upgrades-unsafe-allow constructor
  constructor() {
    // Mark the implementation as already initialized in its own storage. A proxy starts from
    // zeroed storage, so `initialize` remains available only through the proxy instance.
    underlyingToken = IERC20Detailed(address(1));
  }

  /// @notice initialize the contract
  /// @param _underlyingToken address of the underlying token
  /// @param _vault ERC4626 vault where funds will be deployed
  /// @param _idleCDO IdleCDOEpochVariant contract allowed to pull funds
  /// @param _owner owner address
  /// @param _manager routine manager allowed to operate facility admin actions
  function initialize(address _underlyingToken, address _vault, address _idleCDO, address _owner, address _manager) external initializer {
    if (address(underlyingToken) != address(0)) revert AlreadyInitialized();
    if (
      _underlyingToken == address(0) || _vault == address(0) || _owner == address(0) || 
      _manager == address(0) || _idleCDO == address(0) || IERC4626(_vault).asset() != _underlyingToken
    ) {
      revert InvalidAddress();
    }

    __Ownable_init();
    __ReentrancyGuard_init();
    transferOwnership(_owner);

    underlyingToken = IERC20Detailed(_underlyingToken);
    vault = IERC4626(_vault);
    idleCDO = _idleCDO;
    manager = _manager;

    // Set approvals for vault and IdleCDO
    _allowUnlimitedSpend(_underlyingToken, _vault);
    _allowUnlimitedSpend(_underlyingToken, _idleCDO);
  }

  /// @notice Set or clear the routine manager role.
  /// @dev The owner can set this to the zero address to disable manager permissions.
  /// @param _manager manager address, or zero to clear the role
  function setManager(address _manager) external onlyOwner {
    manager = _manager;
  }

  /// @notice Set the vault used to deploy idle funds.
  /// @dev Owner or manager. This does not migrate an existing position. The operator must first
  /// withdraw from the old vault and wait until epoch accounting is inactive, otherwise assets can
  /// remain stranded there and the live accounting views will stop including them after the switch.
  /// @param _vault new ERC4626 vault address
  function setVault(address _vault) external {
    _checkOnlyOwnerOrManager();
    if (_vault == address(0) || IERC4626(_vault).asset() != address(underlyingToken)) {
      revert InvalidAddress();
    }
    // Switching the accounting source is only safe once the current epoch is fully settled and the
    // old vault position has been unwound.
    if (epochAccountingActive || vault.balanceOf(address(this)) != 0) revert NotAllowed();
    underlyingToken.safeApprove(address(vault), 0);
    vault = IERC4626(_vault);
    _allowUnlimitedSpend(address(underlyingToken), _vault);
    emit VaultUpdated(_vault);
  }

  /// @notice Set the real borrower allowed to draw and repay funds.
  /// @dev Owner or manager. This is only allowed while the facility is idle with no borrower-side
  /// principal or interest exposure left to reconcile.
  /// @param _borrower borrower EOA or controller address
  function setBorrower(address _borrower) external {
    _checkOnlyOwnerOrManager();
    if (_borrower == address(0)) revert InvalidAddress();
    // Reassigning the borrower is unsafe while an epoch is active or while the previous borrower
    // still owes principal / interest, because repayment rights would move to a different address.
    if (epochAccountingActive || borrowerPrincipal != 0 || borrowerInterestAccrued != 0 || borrowerInterestDebt != 0) {
      revert NotAllowed();
    }
    borrower = _borrower;
    emit BorrowerSet(_borrower);
  }

  /// @notice Set the fixed APR charged on drawn borrower principal (100e18 = 100% APR).
  /// @dev Owner or manager. Checkpoints accrued interest at the old rate before applying the new APR.
  /// @param _apr borrower APR expressed as a percentage scaled by 1e18
  function setBorrowerApr(uint256 _apr) external {
    _checkOnlyOwnerOrManager();
    _accrueBorrowerInterest();
    borrowerApr = _apr;
    emit BorrowerAprSet(_apr);
  }

  /// @notice Hook called by IdleCDOEpochVariant when a new epoch starts.
  /// It deposits all on-hand assets into the vault and starts accounting.
  /// @param _pendingWithdraws pending withdraw requests amount to reserve for epoch end.
  function onStartEpoch(uint256 _pendingWithdraws) external nonReentrant {
    _checkOnlyIdleCDO();
    _accrueBorrowerInterest();
    // Reserve the amount IdleCDO expects to pull back at stopEpoch before the real borrower can draw again.
    epochPendingWithdraws = _pendingWithdraws;
    uint256 currentVaultAssets = _currentVaultAssets();
    uint256 bufferStartAssets = bufferStartVaultAssets;
    // Carry vault PnL generated while the pool was in the buffer into the new active epoch so it
    // is eventually realized in tranche prices at the next stopEpoch.
    bufferedVaultDelta = int256(currentVaultAssets) - int256(bufferStartAssets);
    bufferStartVaultAssets = 0;
    // Snapshot total assets before re-depositing idle cash so the epoch principal baseline uses the
    // exact pre-deposit amount instead of a post-deposit share-conversion round-down.
    uint256 startAssets = underlyingToken.balanceOf(address(this)) + currentVaultAssets;
    // Any idle balance left on the contract between epochs is parked immediately into the vault.
    _depositAllToVaultInternal(0);
    // Reset the epoch accounting baseline from the exact pre-start total assets so the new epoch
    // does not treat the just-deposited idle balance as fresh vault profit or loss.
    epochStartVaultAssets = startAssets;
    epochDepositedToVault = 0;
    epochWithdrawnFromVault = 0;
    epochAccountingActive = true;
    emit EpochAccountingStarted(startAssets);
  }

  /// @notice Hook called by IdleCDOEpochVariant before stopping an epoch.
  /// Withdraws enough liquidity from the vault so IdleCDO can pull funds.
  /// @param _amountRequired total amount IdleCDO will pull via transferFrom.
  function onStopEpoch(uint256 _amountRequired) external nonReentrant {
    _checkOnlyIdleCDO();
    _accrueBorrowerInterest();

    uint256 onHand = underlyingToken.balanceOf(address(this));
    if (_amountRequired > onHand) {
      uint256 shortfall = _amountRequired - onHand;
      // Do the same thing as the borrower draw path: ask the vault for the exact shortfall and let
      // the hook revert if the vault cannot serve it. IdleCDO catches that revert and treats the
      // stop flow as a borrower default. This avoids depending on vaults whose `maxWithdraw`
      // bookkeeping is conservative or simply broken.
      if (shortfall > 0) {
        uint256 shares = vault.withdraw(shortfall, address(this), address(this));
        if (epochAccountingActive) {
          epochWithdrawnFromVault += shortfall;
        }
        emit WithdrawnFromVault(shortfall, shares, address(this));
      }
    }

    // `totalInterestDueNow()` was already read by IdleCDO before calling this hook, so once the
    // stop flow begins we can clear the previous carry and snapshot the remaining vault sleeve
    // as the baseline for measuring buffer-period vault PnL before the next epoch starts.
    bufferedVaultDelta = 0;
    bufferStartVaultAssets = _currentVaultAssets();

    // Stop reserving epoch-end withdraw liquidity once IdleCDO has started the stop flow.
    epochPendingWithdraws = 0;
    epochAccountingActive = false;
    emit EpochAccountingStopped();
  }

  /// @notice Settle accrued borrower interest into debt after IdleCDO successfully fronted it.
  /// @dev Called by IdleCDO only on the success path of `stopEpoch`. If the CDO's `transferFrom`
  /// fails (default), this is never called and borrower interest stays in `borrowerInterestAccrued`.
  /// Borrower debt is intentionally settled at the full contractual borrower-interest amount,
  /// without netting vault gains or losses against it.
  function settleBorrowerInterest() external nonReentrant {
    _checkOnlyIdleCDO();
    uint256 settled = borrowerInterestAccrued;
    if (settled != 0) {
      borrowerInterestAccrued = 0;
      borrowerInterestDebt += settled;
    }
    emit BorrowerInterestSettled(settled);
  }

  /// @notice interest accrued in the vault since the last `startEpochAccounting`
  function vaultInterestAccrued() external view returns (uint256) {
    (uint256 interest,) = _vaultNetInterest();
    return interest;
  }

  /// @notice borrower interest accrued since epoch start up to now (includes uncheckpointed interest)
  function borrowerInterestAccruedNow() public view returns (uint256) {
    return borrowerInterestAccrued + _pendingBorrowerInterest(borrowerPrincipal, lastBorrowerAccrual);
  }

  /// @notice total borrower interest still owed by the real borrower
  function borrowerInterestOwedNow() public view returns (uint256) {
    return borrowerInterestDebt + borrowerInterestAccruedNow();
  }

  /// @notice unrealized loss from the vault position since epoch start
  function vaultLoss() external view returns (uint256) {
    (,uint256 loss) = _vaultNetInterest();
    return loss;
  }

  /// @notice Total net epoch interest due to the pool at stop.
  /// @dev This is the single value read by IdleCDO to price the epoch: borrower contractual
  /// interest plus positive vault PnL minus vault losses. It is a pool-facing value, so it can
  /// be lower than `borrowerInterestDebt` when the borrower still owes full contractual interest
  /// but the vault sleeve suffered a loss.
  function totalInterestDueNow() external view returns (uint256) {
    (uint256 vaultInterest, uint256 loss) = _vaultNetInterest();
    uint256 totalGain = vaultInterest + borrowerInterestAccruedNow();
    return totalGain > loss ? totalGain - loss : 0;
  }

  /// @notice Compute the net vault delta split into interest and loss (mutually exclusive).
  function _vaultNetInterest() internal view returns (uint256 interest, uint256 loss) {
    if (!epochAccountingActive) return (0, 0);
    uint256 earnedAssets = _currentVaultAssets() + epochWithdrawnFromVault;
    uint256 principalAssets = epochStartVaultAssets + epochDepositedToVault;
    int256 netDelta = bufferedVaultDelta + int256(earnedAssets) - int256(principalAssets);
    if (netDelta > 0) {
      interest = uint256(netDelta);
    } else {
      loss = uint256(-netDelta);
    }
  }

  /// @notice current borrowable liquidity excluding reserved withdraw requests
  function availableToBorrow() public view returns (uint256) {
    uint256 totalAssets = underlyingToken.balanceOf(address(this)) + _currentVaultAssets();
    // Interest is minted (not pulled as cash), so only pending withdraw requests need reservation.
    uint256 reserved = epochPendingWithdraws;
    return totalAssets <= reserved ? 0 : totalAssets - reserved;
  }

  /// @notice Emergency escape: redeem vault shares back to this contract.
  /// @dev Owner or manager. Pass 0 to redeem all shares.
  /// @param _shares number of vault shares to redeem (0 = redeem all)
  /// @return assets amount of underlying redeemed
  function emergencyExitVault(uint256 _shares) external nonReentrant returns (uint256 assets) {
    _checkOnlyOwnerOrManager();
    if (_shares == 0) {
      _shares = vault.balanceOf(address(this));
    }
    if (_shares == 0) revert InvalidAmount();
    assets = vault.redeem(_shares, address(this), address(this));
    if (epochAccountingActive) {
      epochWithdrawnFromVault += assets;
    }
    emit RedeemedFromVault(_shares, assets, address(this));
  }

  /// @notice Move the contract's full idle underlying balance into the vault.
  /// @param _principalAssets Portion of the deposited assets that should extend the epoch principal
  /// baseline instead of being recognized as current-epoch profit.
  function _depositAllToVaultInternal(uint256 _principalAssets) internal {
    uint256 assets = underlyingToken.balanceOf(address(this));
    if (assets == 0) return;
    uint256 shares = vault.deposit(assets, address(this));
    if (epochAccountingActive && _principalAssets != 0) {
      epochDepositedToVault += _principalAssets;
    }
    emit DepositedIntoVault(assets, shares);
  }

  /// @notice Draw funds from the revolving-credit facility.
  /// @dev Only the configured borrower address can call this while an epoch is active. If there is
  /// not enough on-hand liquidity, the shortfall is first withdrawn from the vault.
  /// @param assets amount of underlying to draw
  /// @return withdrawnShares vault shares burned, if any liquidity had to be freed first
  function borrow(uint256 assets) external nonReentrant returns (uint256 withdrawnShares) {
    if (msg.sender != borrower || !epochAccountingActive) revert NotAllowed();
    if (assets == 0) revert InvalidAmount();

    // Borrows are capped by the live "reserved vs free" view so epoch-end obligations always stay covered.
    if (assets > availableToBorrow()) revert InsufficientBorrowable();

    _accrueBorrowerInterest();

    uint256 onHand = underlyingToken.balanceOf(address(this));
    if (onHand < assets) {
      uint256 shortfall = assets - onHand;
      withdrawnShares = vault.withdraw(shortfall, address(this), address(this));
      if (epochAccountingActive) {
        epochWithdrawnFromVault += shortfall;
      }
      emit WithdrawnFromVault(shortfall, withdrawnShares, address(this));
    }

    borrowerPrincipal += assets;
    underlyingToken.safeTransfer(borrower, assets);
    emit Borrowed(assets);
  }

  /// @notice Repay drawn funds back into the facility.
  /// @dev Repayments are applied in this order:
  /// 1. `borrowerInterestDebt` already fronted by IdleCDO
  /// 2. `borrowerInterestAccrued` not yet fronted
  /// 3. `borrowerPrincipal`
  ///
  /// Passing `assets = 0` repays the full currently tracked obligation.
  ///
  /// Any excess over the tracked debt simply remains on this contract. When an epoch is active,
  /// the received funds are redeployed into the vault before the function returns.
  /// @param assets amount of underlying to repay (`0` = repay all currently owed)
  /// @return interestPaid interest component cleared by the repayment
  /// @return principalPaid principal component cleared by the repayment
  function repay(uint256 assets) external nonReentrant returns (uint256 interestPaid, uint256 principalPaid) {
    if (msg.sender != borrower) revert NotAllowed();

    if (assets == 0) {
      assets = borrowerPrincipal + borrowerInterestOwedNow();
      if (assets == 0) revert InvalidAmount();
    }

    _accrueBorrowerInterest();

    underlyingToken.safeTransferFrom(borrower, address(this), assets);
    uint256 totalRepaidAssets = assets;
    uint256 currentEpochInterestPaid;

    // First clear interest that IdleCDO already fronted during previous epoch settlements.
    uint256 settledInterestDue = borrowerInterestDebt;
    if (settledInterestDue != 0) {
      if (assets >= settledInterestDue) {
        interestPaid = settledInterestDue;
        borrowerInterestDebt = 0;
        assets -= settledInterestDue;
      } else {
        borrowerInterestDebt = settledInterestDue - assets;
        emit Repaid(assets, assets, 0);
        if (epochAccountingActive) {
          // While an epoch is active, even partial repayments are parked back into the vault immediately.
          // This repayment only clears previously-fronted debt, so it should not count as new epoch profit.
          _depositAllToVaultInternal(assets);
        }
        return (assets, 0);
      }
    }

    // Then clear interest accrued but not yet fronted by IdleCDO.
    uint256 accruedInterestDue = borrowerInterestAccrued;
    if (assets >= accruedInterestDue) {
      interestPaid += accruedInterestDue;
      currentEpochInterestPaid = accruedInterestDue;
      borrowerInterestAccrued = 0;
      assets -= accruedInterestDue;

      // Only after all interest is covered can the remainder reduce outstanding principal.
      uint256 principalDue = borrowerPrincipal;
      principalPaid = assets > principalDue ? principalDue : assets;
      borrowerPrincipal = principalDue - principalPaid;
    } else {
      interestPaid += assets;
      currentEpochInterestPaid = assets;
      borrowerInterestAccrued = accruedInterestDue - assets;
    }

    emit Repaid(interestPaid + principalPaid, interestPaid, principalPaid);
    if (epochAccountingActive) {
      // Current-epoch borrower interest must remain visible as profit at stopEpoch, while principal,
      // previously-fronted debt, and any excess repayment should only extend the epoch principal baseline.
      _depositAllToVaultInternal(totalRepaidAssets - currentEpochInterestPaid);
    }
  }

  /// @notice Return the total exposure in underlying terms (on-hand plus vault position).
  function totalUnderlying() external view returns (uint256) {
    return underlyingToken.balanceOf(address(this)) + _currentVaultAssets();
  }

  /// @notice Return the current vault share balance held by this contract.
  function vaultSharesBalance() external view returns (uint256) {
    return vault.balanceOf(address(this));
  }

  /// @notice Convert the current vault share position into underlying terms.
  function _currentVaultAssets() internal view returns (uint256) {
    uint256 shares = vault.balanceOf(address(this));
    return shares == 0 ? 0 : vault.convertToAssets(shares);
  }

  /// @notice Compute uncheckpointed borrower interest since the last accrual timestamp.
  /// @dev `borrowerApr` is stored as a percentage scaled by `1e18`, so dividing by 100 converts
  /// it into a `1e18`-scaled rate fraction before prorating it over a year.
  function _pendingBorrowerInterest(uint256 principal, uint256 last) internal view returns (uint256) {
    if (principal == 0 || last == 0 || borrowerApr == 0) return 0;
    uint256 elapsed = block.timestamp - last;
    return elapsed == 0 ? 0 : _calcInterest(principal, elapsed);
  }

  /// @notice Compute simple time-based borrower interest for a principal over an elapsed period.
  function _calcInterest(uint256 principal, uint256 elapsed) internal view returns (uint256) {
    return principal * (borrowerApr / 100) * elapsed / (YEAR * ONE_TRANCHE_TOKEN);
  }

  /// @notice Checkpoint borrower interest up to `block.timestamp`.
  /// @dev The first call only seeds the accrual clock. When principal or APR is zero we still
  /// move the timestamp forward so interest starts accruing cleanly from the next state change.
  function _accrueBorrowerInterest() internal {
    uint256 last = lastBorrowerAccrual;
    uint256 principal = borrowerPrincipal;
    if (last == 0 || principal == 0 || borrowerApr == 0) {
      lastBorrowerAccrual = block.timestamp;
      return;
    }
    uint256 elapsed = block.timestamp - last;
    if (elapsed == 0) return;
    borrowerInterestAccrued += _calcInterest(principal, elapsed);
    lastBorrowerAccrual = block.timestamp;
  }

  /// @notice Revert unless the caller is the configured IdleCDO.
  function _checkOnlyIdleCDO() internal view {
    if (msg.sender != idleCDO) revert NotAllowed();
  }

  /// @notice Revert unless the caller is the owner or configured manager.
  function _checkOnlyOwnerOrManager() internal view {
    if (msg.sender != owner() && msg.sender != manager) revert NotAllowed();
  }

  /// @notice Emergency token rescue.
  /// @dev This is fully owner-trusted and can move the underlying as well, so it should only be
  /// used to recover stuck funds or to unwind a broken external integration.
  /// @param _token token address to transfer
  /// @param _to recipient
  /// @param _amount amount to transfer
  function rescueTokens(address _token, address _to, uint256 _amount) external onlyOwner {
    if (_to == address(0)) revert InvalidAddress();
    IERC20Detailed(_token).safeTransfer(_to, _amount);
  }

  /// @dev Set allowance for `_token` to unlimited for `_spender`.
  /// Both the vault and IdleCDO are trusted integrations, so the contract keeps a standing approval.
  /// @param _token token address
  /// @param _spender spender address
  function _allowUnlimitedSpend(address _token, address _spender) internal {
    IERC20Detailed(_token).safeIncreaseAllowance(_spender, type(uint256).max);
  }
}
